config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only: [:create, :destroy]  
  end  
  resources :users, only: [:edit, :index, :show,  :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length:{ maximum: 200}
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_one_attached :profile_image
  validates :name, presence: true, length: {minimum: 2, maximum: 20},uniqueness: true
  validates :introduction, length: {maximum: 50}
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top, :about]
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        user_path(current_user.id)
    end
    
    def after_sign_out_path_for(resource)
        root_path
    end
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    book_user = @book.user_id
    @user = User.find_by_id(book_user)
    @comment = BookComment.new
  end

  def edit
    user_id = Book.find(params[:id]).user_id
    if user_id == current_user.id
      @book = Book.find(params[:id])
    else
      redirect_to books_path
    end
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else 
      @books = Book.all
      @user = current_user
      render :index
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else 
      render :edit
    end
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else 
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_detail.html.erb
<h2>Book detail</h2>
<table class = "table table-hover table-inverse">
  <tbody>
      <% id = book.user_id %>
      <tr>
      <td><a href = <%= user_path(id)%> ><%= image_tag book.user.get_profile_image(100,100) %>
            <br>
          <%= book.user.name %>
          </a></td>
      <td><%= link_to book.title , book_path(book.id) %></td>
      <td><%= book.body %></td>

      <% if current_user.id == book.user_id %>
        <td><%= link_to "Edit", edit_book_path(book.id) , class: 'btn btn-sm btn-success'%></td>
        <td><%= link_to "Destroy", book_path(book.id) ,class: 'btn btn-sm btn-danger', method: :delete,  data: { confirm: "本当に消しますか？" } %></td>
      <% end %>

      <% if book.favorited_by?(current_user) %>
      <td>
        <%= link_to book_favorites_path(book), method: :delete do %>
          <span class = "text-danger"><i class="fas fa-heart"></i><%= book.favorites.count %></span>
        <% end %>
      </td>
      <% else %>
      <td>
        <%= link_to book_favorites_path(book), method: :post do %>
          <i class="far fa-heart"></i> <%= book.favorites.count %>
        <% end %>
      </td>
      <% end %>
      <td>
        コメント数: <%= book.book_comments.count%>件
      </td>
      </tr>
  </tbody>
</table>

<div>
  <% book.book_comments.each do |book_comment| %>
    <div>
    <%= image_tag book_comment.user.get_profile_image(100,100) %>
    <%= book_comment.comment %>
    </div>
    <%= link_to user_path(book_comment.user) do %>
    <%= book_comment.user.name %>
    <% end %>
    <% if current_user.id == book_comment.user_id %>
    <%= link_to "Destroy", book_book_comment_path(book,book_comment), method: :delete,class: "btn btn-sm btn-danger" %>
    <% end %>
  <% end %>
</div>
<div>
<%= form_with model: [book, comment] do |f| %>
  <div class = "form-group">
    <%= f.text_area :comment, rows: '5' ,class: "form-control" %>
  </div>
  <div class = "form-group">
    <%= f.submit "送信する" ,class: "btn btn-success"%>
  </div>
  <% end %>
</div>

app/views/books/_list.html.erb
<h2>Books</h2>
<table class = "table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan = "3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <% id = book.user_id %>
      <tr>
      <td><a href = <%= user_path(id)%> ><%= image_tag book.user.get_profile_image(100,100) %>
          </a></td>
      <td><%= link_to book.title , book_path(book.id) %></td>
      <td><%= book.body %></td>
      <% if current_user.id == book.user_id %>
        <td><%= link_to "Edit", edit_book_path(book.id) , class: 'btn btn-sm btn-success'%></td>
        <td><%= link_to "Destroy", book_path(book.id) ,class: 'btn btn-sm btn-danger', method: :delete ,"data-confirm" => "本当に消しますか？" %></td>
      <% else %>
        <!--<td></td>-->
        <!--<td></td>-->
      <% end %>
      <% if book.favorited_by?(current_user) %>
      <td>
        <%= link_to book_favorites_path(book), method: :delete do %>
          <span class = "text-danger"><i class="fas fa-heart"></i><%= book.favorites.count %></span>
        <% end %>
      </td>
      <% else %>
      <td>
        <%= link_to book_favorites_path(book), method: :post do %>
          <i class="far fa-heart"></i> <%= book.favorites.count %>
        <% end %>
      </td>
      <% end %>
      <td>
        コメント数: <%= book.book_comments.count%>件
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <% if @book.errors.count >= 2 %>
            <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <% else %>
            <h3>1 error prohibited this obj from being saved:</h3>
          <% end %>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f|%>
      <div class = "form-group">
        <%= f.label :title %>
        <br>
        <%= f.text_field :title,class: "form-control" %>
      </div>  
      <div class = "form-group">
        <%= f.label :body, "Opinion"%>
        <br>
        <%= f.text_area :body ,class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.submit "Update Book", class: "btn btn-success"%>
      </div>
      <% end %>
      <%= link_to "Show" , book_path(@book.id) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class = "container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <% if @book.errors.count >= 2 %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
  <% else %>
    <h3>1 error prohibited this obj from being saved:</h3>
  <% end %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class = "row mt-3">
    <div class = "col-md-3">
      <%= render "/users/info", user: @user %>
    </div>
    <div class = "col-md-8 offset-md-1">
      <%= render "list", books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class = "container">
  <div class = "row mt-3">
    <div class = "col-md-3">
      <%= render "/users/info", user: @user %>
    </div>
    <div class = "col-md-8 offset-md-1">
      <%= render "detail", book: @book, comment: @comment %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class = "container">
  <div class="row">
<h1 class ="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>
</div>
</div>

app/views/homes/top.html.erb
<div class = "container">
  <div class="row">
    <div class ="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to<i class="fas fa-book"></i><strong>Bookers!</strong></h1>
      <p>In <i class="fas fa-book"></i></i><strong>Bookers</strong></p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class = "btn-wrapper col-10 mx-auto">
        <div class = "row">
            <a class = "btn btn-info btn-sm btn-block mb-3 sign in" href = <%= new_user_session_path%> >Log in</a>
        </div>
        <div class = "row">
            <a class = "btn btn-success btn-sm btn-block mb-3 sign in" href = <%= new_user_registration_path %>>Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--<script src="https://kit.fontawesome.com/ff57667ed8.js" crossorigin="anonymous"></script>-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "d-flex flex-column vh-100">
    <header class = "shadow-sm">
      <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class = "container">
          <a class = "navbar-brand" href="/">Bookers</a>
          <button class = "navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropDown" aria-expanded="false" aria-label="Toggle navigation">
            <span class = "navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class = "nav-item">
              <%= link_to  user_path(current_user.id), class: 'nav-link text-white' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-white' do%>
              <i class="fas fa-users"></i> Users
              <% end %>
            </li>
              <%= link_to  books_path, class: 'nav-link text-white' do %>
              <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  destroy_user_session_path, method: :delete, class: 'nav-link text-white' do%>
              <i class="fas fa-sign-out-alt"></i> logout
              <% end %>
            </li>
            <li class="nav-item">
            <% else %>
            <li class = "nav-item">
              <%= link_to root_path, class: 'nav-link text-white' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  about_path, class: 'nav-link text-white' do %>
              <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li class = "nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
              <i class="fas fa-user-plus"></i> sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  new_user_session_path, class: 'nav-link text-white' do %>
              <i class="fas fa-sign-in-alt"></i> login
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= render 'layouts/messages' %>
    <%= yield %>
    </main>
    <footer class = "bg-white text-dark">
      <div class = "container mt-5">
        <div class = "row">
          <div class = "mx-auto">
            <p>© Infrataop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<h2>
  User info
</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class = "table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class = "row">
  <a href = "/users/<%= user.id %>/edit" class = "btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></a>
</div>
<h2 class = "mt-3">
  New book
</h2>
<%= form_with model: Book.new, url: books_path do |f| %>
  <div class = "form-group">
    <%= f.label :title %> <br>
    <%= f.text_field :title,  class: "form-control" %>
  </div>
  <div class = "form-group">
    <%= f.label :body,"Opinion" %> <br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class = "form-group">
    <%= f.submit "Create Book" , class: "btn btn-success"%>
  </div>
<% end %>

app/views/users/_list.html.erb
<h2>Users</h2>
<table class = "table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan = "3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <% id = user.id %>
      <tr>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>
      <% if @user.errors.any? %>
          <% if @user.errors.count >= 2 %>
            <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
          <% else %>
            <h3>1 error prohibited this obj from being saved:</h3>
          <% end %>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f|%>
      <div class = "form-group">
        <%= f.label :name  %>
        <br>
        <%= f.text_field :name,class: "form-control" %>
      </div>  
      <div class = "form-group">
        <%= f.label :profile_image, "Image" %>
        <br>
        <%= f.file_field :profile_image, accept: "image/*" %>
      </div>
      <div class = "form-group">
        <%= f.label :introduction, "Introduction"%>
        <br>
        <%= f.text_area :introduction ,class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.submit "Update User", class: "btn btn-secondary"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class = "container">
  <div class = "row mt-3">
    <div class = "col-md-3">
      <%= render "info", user: @user %>
    </div>
    <div class = "col-md-8 offset-md-1">
      <%= render "list", users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container px-5 px-sm-0 mt-3">
  <div class = "row">
    <div class = "col-md-3">
      <%= render "info", user: @user %>
    </div>
    <div class = "col-md-8 offset-md-1">
      <%= render "books/list", books: @books %>
    </div>
  </div>
  
</div>